const HTML_PAGE_TYPES = {
    ABOUT_US: 'ABOUT_US',
    TERMS_AND_CONDITIONS: 'TERMS_AND_CONDITIONS',
    PRIVACY_POLICY: 'PRIVACY_POLICY',
    RETURN_REFUND_POLICY: 'RETURN_REFUND_POLICY',
    SHIPPING_POLICY: 'SHIPPING_POLICY',
};

module.exports = {HTML_PAGE_TYPES};